stages:
	- prep
	- test
	- deploy

before_script:
	stage: prep
	script:
	- echo "preparing environment"
	- virtualenv env
	- . env/bin/activate
	- pip install -r pip-packages.txt

test:
	stage: test
	script: 
	- echo "Running tests"
	- . env/bin/activate
	- python3 src/manage.py check


deploy_staging:
	stage: deploy
	script:
		- echo "Deploy to staging server"
	environment:
		name: stage
		url: https://portal.ucc.asn.au/stage
	only:
	- master

	deploy_prod:
	stage: deploy
	script:
		- echo "Deploy to production server"
	environment:
		name: production
		url: https://portal.ucc.asn.au
	when: manual
	only:
	- master

deploy_test:
	stage: deploy
	script:
		- echo "Deploy to test"
	environment:
		name: test-$CI_COMMIT_REF_NAME
		url: https://portal.ucc.asn.au/test/$CI_COMMIT_REF_NAME
	except:
	- master