stages:
  - test
  - deploy

before_script:
  - echo "preparing environment"
  - virtualenv env -p `which python3`
  - . env/bin/activate
  - pip install -r pip-packages.txt
  
  
test:
  stage: test
  script:
    - echo "Running tests"

deploy_test:
  stage: deploy
  tags:
    - test
  script:
    - echo "Deploy to test"
    - rm -f /var/www/test/$CI_COMMIT_REF_NAME
    - ln -srT ./ /var/www/test/$CI_COMMIT_REF_NAME
    - envsubst < src/gms/settings_local.example.py > src/gms/settings_local.py
    - python src/manage.py makemigrations
    - python src/manage.py migrate --run-syncdb
    - ln -s /etc/uwsgi/vassals/test.skel /etc/uwsgi/vassals/$CI_COMMIT_REF_NAME.ini
  environment:
    name: test/$CI_COMMIT_REF_NAME
    url: https://$CI_COMMIT_REF_NAME.test.ucc.asn.au
  except:
      - master
