# Generated by Django 2.1.5 on 2019-01-29 04:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('memberdb', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('amount', models.IntegerField(verbose_name='Amount in cents')),
                ('idempotency_key', models.CharField(default=uuid.uuid1, max_length=64, verbose_name='Square Transactions API idempotency key')),
                ('is_paid', models.BooleanField(blank=True, default=False, verbose_name='Has been paid')),
                ('dispense_synced', models.BooleanField(blank=True, default=False, verbose_name='Payment logged in dispense')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('date_paid', models.DateTimeField(blank=True, null=True, verbose_name='Date paid (payment captured)')),
            ],
        ),
        migrations.CreateModel(
            name='MembershipPayment',
            fields=[
                ('cardpayment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='squarepay.CardPayment')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='memberdb.Membership')),
            ],
            bases=('squarepay.cardpayment',),
        ),
    ]
